import 'package:flutter/material.dart';

import 'database_helper.dart';

void main() {
  runApp(const TactilePOSApp());
}

class Product {
  final int? id; // NEW: The database needs a unique ID for every row
  final String name;
  final String description;
  final double price;
  final String image;
  final String category;
  final String? tag;
  final Color? tagColor;

  const Product({
    this.id, // ID is optional because it gets auto-generated by SQLite when we create a new item
    required this.name,
    required this.description,
    required this.price,
    required this.image,
    required this.category,
    this.tag,
    this.tagColor,
  });

  // Convert a Product into a Map so SQLite can save it
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'description': description,
      'price': price,
      'image': image,
      'category': category,
      'tag': tag,
      'tagColor': tagColor?.toARGB32(), // Convert Color to an integer
    };
  }

  // Build a Product back out of a SQLite Map
  factory Product.fromMap(Map<String, dynamic> map) {
    return Product(
      id: map['id'],
      name: map['name'],
      description: map['description'],
      price: map['price'],
      image: map['image'],
      category: map['category'],
      tag: map['tag'],
      tagColor: map['tagColor'] != null ? Color(map['tagColor']) : null, // Convert integer back to Color
    );
  }
}


class CartItem {
  final Product product;
  int quantity;
  final String modifiers;

  CartItem({
    required this.product,
    this.quantity = 1,
    this.modifiers = 'Regular', // Default modifier
  });
}

class CartState extends ChangeNotifier {
  final List<CartItem> _items = [];

  // Getters for our UI to read
  List<CartItem> get items => _items;
  double get subtotal => _items.fold(0, (sum, item) => sum + (item.product.price * item.quantity));
  double get tax => subtotal * 0.08; // Fixed 8% tax rate for now
  double get total => subtotal + tax;

  // Action: Add to Cart
  void addItem(Product product) {
    // Check if the item is already in the cart
    final existingIndex = _items.indexWhere((item) => item.product.name == product.name);

    if (existingIndex >= 0) {
      _items[existingIndex].quantity++; // Increase quantity if it exists
    } else {
      _items.add(CartItem(product: product)); // Add new if it doesn't
    }

    // CRITICAL: This tells the Flutter UI to redraw itself!
    notifyListeners();
  }

  // Action: Change Quantity (or remove if 0)
  void updateQuantity(CartItem item, int delta) {
    item.quantity += delta;
    if (item.quantity <= 0) {
      _items.remove(item);
    }
    notifyListeners();
  }

  // Action: Clear the cart after checkout
  void clearCart() {
    _items.clear();
    notifyListeners();
  }
}

final cartState = CartState();

class TactilePOSApp extends StatelessWidget {
  const TactilePOSApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Tactile POS',
      theme: ThemeData(
        // The background of the center area (soft off-white)
        scaffoldBackgroundColor: const Color(0xFFFCF8F8),
        colorScheme: ColorScheme.fromSeed(
          // The dark green used for buttons and active states
          seedColor: const Color(0xFF006E3B),
        ),
        useMaterial3: true,
      ),
      home: const POSMainLayout(),
    );
  }
}

class POSMainLayout extends StatelessWidget {
  const POSMainLayout({super.key});

  @override
  Widget build(BuildContext context) {
    // Grab the screen width
    final screenWidth = MediaQuery.of(context).size.width;
    // We consider anything less than 950 pixels to be "Portrait" or a smaller screen
    final isPortrait = screenWidth < 950;

    return Scaffold(
      // NEW: The Drawer will hold our Cart when the screen is too narrow!
      endDrawer: isPortrait ? const Drawer(
        child: POSActiveOrderSidebar(),
      ) : null,
      body: Row(
        children: [
          // 1. LEFT NAVIGATION PANEL (Always visible)
          const POSSideNav(),
          const VerticalDivider(width: 1, thickness: 1, color: Color(0xFFEEDDDD)),

          // 2. CENTER CONTENT AREA
          const Expanded(
            child: POSCenterArea(),
          ),

          // 3. RIGHT ACTIVE ORDER SIDEBAR (Only visible if we have wide screen space)
          if (!isPortrait)
            const POSActiveOrderSidebar(),
        ],
      ),
    );
  }
}

class POSSideNav extends StatelessWidget {
  const POSSideNav({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 90,
      color: const Color(0xFFFCF8F8),
      child: Column(
        children: [
          const SizedBox(height: 24),
          // Top Logo
          const Icon(Icons.coffee, size: 32, color: Colors.black87),
          const SizedBox(height: 48),

          // Navigation Items
          _buildNavItem(Icons.point_of_sale, 'Register', isActive: true),
          const SizedBox(height: 16),
          _buildNavItem(Icons.receipt_long, 'Orders'),
          const SizedBox(height: 16),
          _buildNavItem(Icons.inventory_2_outlined, 'Inventory'),
          const SizedBox(height: 16),
          _buildNavItem(Icons.people_outline, 'Customers'),
          const SizedBox(height: 16),
          _buildNavItem(Icons.bar_chart, 'Reports'),

          // Pushes the bottom items down
          const Spacer(),

          // Bottom Profile & Logout
          const CircleAvatar(
            radius: 18,
            backgroundImage: NetworkImage('https://i.pravatar.cc/150?img=11'), // Temporary mock avatar
          ),
          const SizedBox(height: 16),
          const Icon(Icons.logout, color: Colors.black54),
          const SizedBox(height: 24),
        ],
      ),
    );
  }

  // Helper method to build consistent navigation buttons
  Widget _buildNavItem(IconData icon, String label, {bool isActive = false}) {
    return Container(
      width: 68,
      padding: const EdgeInsets.symmetric(vertical: 12),
      decoration: BoxDecoration(
        color: isActive ? const Color(0xFF006E3B) : Colors.transparent,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(
            icon,
            color: isActive ? Colors.white : Colors.black54,
            size: 28,
          ),
          const SizedBox(height: 4),
          Text(
            label,
            style: TextStyle(
              fontSize: 10,
              fontWeight: isActive ? FontWeight.bold : FontWeight.normal,
              color: isActive ? Colors.white : Colors.black54,
            ),
          ),
        ],
      ),
    );

  }
}

class POSCenterArea extends StatefulWidget {
  const POSCenterArea({super.key});

  @override
  State<POSCenterArea> createState() => _POSCenterAreaState();
}

class _POSCenterAreaState extends State<POSCenterArea> {
  String selectedCategory = 'All Items';
  String searchQuery = '';

  // 1. The memory for our database products
  List<Product> products = [];
  bool isLoading = true; // Tells the UI to show a loading spinner

  @override
  void initState() {
    super.initState();
    _loadMenuFromDatabase(); // 2. Fetch data as soon as the screen loads
  }

  Future<void> _loadMenuFromDatabase() async {
    // Check what is currently in the hard drive
    final dbProducts = await DatabaseHelper.instance.getAllProducts();

    if (dbProducts.isEmpty) {
      // 3. SEEDING: If the DB is empty, insert our default menu
      final defaultMenu = [
        const Product(name: 'Velvet Oat Latte', description: 'Double shot, steamed oat milk, vanilla bean.', price: 5.50, image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500&q=80', category: 'Espresso', tag: 'POPULAR', tagColor: Color(0xFF006E3B)),
        const Product(name: 'Almond Croissant', description: 'Twice-baked with house frangipane.', price: 4.75, image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&q=80', category: 'Pastry'),
        const Product(name: 'Ethiopian Cold Brew', description: '18-hour steep, notes of blueberry & lime.', price: 6.00, image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500&q=80', category: 'Brew', tag: 'SEASONAL', tagColor: Color(0xFF8B5A2B)),
        const Product(name: 'Classic Flat White', description: 'Ristretto shots with velvety microfoam.', price: 4.50, image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=500&q=80', category: 'Espresso'),
      ];

      for (var item in defaultMenu) {
        await DatabaseHelper.instance.insertProduct(item);
      }

      // Fetch again now that we inserted them
      final newDbProducts = await DatabaseHelper.instance.getAllProducts();
      setState(() {
        products = newDbProducts;
        isLoading = false;
      });
    } else {
      // DB already had items, just show them
      setState(() {
        products = dbProducts;
        isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    // Our upgraded filter logic remains exactly the same!
    final filteredProducts = products.where((p) {
      final matchesCategory = selectedCategory == 'All Items' || p.category == selectedCategory;
      final matchesSearch = p.name.toLowerCase().contains(searchQuery.toLowerCase());
      return matchesCategory && matchesSearch;
    }).toList();

    return Container(
      color: const Color(0xFFFCF8F8),
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header Row
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Tactile POS', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, letterSpacing: -0.5)),
                  Text('Main Counter • Shift: Morning Crew', style: TextStyle(fontSize: 14, color: Colors.grey)),
                ],
              ),
              Container(
                width: 300,
                height: 48,
                decoration: BoxDecoration(color: const Color(0xFFFDECE9), borderRadius: BorderRadius.circular(24)),
                child: TextField(
                  onChanged: (value) {
                    setState(() {
                      searchQuery = value;
                    });
                  },
                  decoration: const InputDecoration(
                    hintText: 'Search menu...',
                    hintStyle: TextStyle(color: Colors.black38, fontSize: 14),
                    prefixIcon: Icon(Icons.search, color: Colors.black54),
                    border: InputBorder.none,
                    contentPadding: EdgeInsets.symmetric(vertical: 14),
                  ),
                ),
              ),
              Row(
                children: [
                  IconButton(onPressed: () {}, icon: const Icon(Icons.notifications_none, color: Colors.black87)),
                  IconButton(onPressed: () {}, icon: const Icon(Icons.settings_outlined, color: Colors.black87)),
                  IconButton(onPressed: () {}, icon: const Icon(Icons.sync, color: Colors.black87)),

                  // NEW: Cart button that only shows on narrow screens
                  if (MediaQuery.of(context).size.width < 950)
                    IconButton(
                      onPressed: () {
                        // This opens the slide-out drawer we just added!
                        Scaffold.of(context).openEndDrawer();
                      },
                      icon: const Icon(Icons.shopping_cart_outlined, color: Color(0xFF006E3B), size: 28),
                    ),
                ],
              ),
            ],
          ),

          const SizedBox(height: 32),

          // Category Chips
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Row(
              children: [
                _buildChip('All Items'),
                _buildChip('Espresso'),
                _buildChip('Brew'),
                _buildChip('Pastry'),
              ],
            ),
          ),

          const SizedBox(height: 24),

          // 4. The Product Grid (Now with a Loading Spinner!)
          // The Product Grid
          Expanded(
            child: isLoading
                ? const Center(child: CircularProgressIndicator(color: Color(0xFF006E3B)))
                : GridView.builder(
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                // NEW: Dynamically change columns based on screen width!
                crossAxisCount: MediaQuery.of(context).size.width < 950 ? 2 : 3,
                crossAxisSpacing: 20,
                mainAxisSpacing: 20,
                childAspectRatio: 0.75,
              ),
              itemCount: filteredProducts.length,
              itemBuilder: (context, index) {
                return _buildProductCard(context, filteredProducts[index]);
              },
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildChip(String label) {
    final isActive = selectedCategory == label;
    return Padding(
      padding: const EdgeInsets.only(right: 12.0),
      child: InkWell(
        onTap: () {
          setState(() {
            selectedCategory = label;
          });
        },
        borderRadius: BorderRadius.circular(24),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 10),
          decoration: BoxDecoration(
            color: isActive ? const Color(0xFF006E3B) : const Color(0xFFFDECE9),
            borderRadius: BorderRadius.circular(24),
          ),
          child: Text(
            label,
            style: TextStyle(fontWeight: FontWeight.bold, color: isActive ? Colors.white : Colors.black87),
          ),
        ),
      ),
    );
  }

  Widget _buildProductCard(BuildContext context, Product product) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(color: Colors.black.withValues(alpha: 0.03), blurRadius: 10, offset: const Offset(0, 4)),
        ],
      ),
      child: Padding(
        padding: const EdgeInsets.all(12.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Stack(
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: Image.network(product.image, height: 120, width: double.infinity, fit: BoxFit.cover),
                ),
                if (product.tag != null)
                  Positioned(
                    top: 8, right: 8,
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                      decoration: BoxDecoration(color: product.tagColor, borderRadius: BorderRadius.circular(8)),
                      child: Text(product.tag!, style: const TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.bold)),
                    ),
                  ),
              ],
            ),
            const SizedBox(height: 12),
            Text(product.name, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, letterSpacing: -0.5), maxLines: 1, overflow: TextOverflow.ellipsis),
            const SizedBox(height: 4),
            Text(product.description, style: TextStyle(color: Colors.grey[600], fontSize: 12, height: 1.3), maxLines: 2, overflow: TextOverflow.ellipsis),
            const Spacer(),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text('\$${product.price.toStringAsFixed(2)}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                Container(
                  decoration: const BoxDecoration(color: Color(0xFF006E3B), shape: BoxShape.circle),
                  child: IconButton(
                    iconSize: 20, padding: const EdgeInsets.all(8), constraints: const BoxConstraints(),
                    icon: const Icon(Icons.add, color: Colors.white),
                    onPressed: () {
                      cartState.addItem(product);
                      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('${product.name} added to order!'), duration: const Duration(milliseconds: 800), behavior: SnackBarBehavior.floating));
                    },
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class POSActiveOrderSidebar extends StatelessWidget {
  const POSActiveOrderSidebar({super.key});

  @override
  Widget build(BuildContext context) {
    // 1. Wrap the entire sidebar in a ListenableBuilder
    return ListenableBuilder(
        listenable: cartState,
        builder: (context, child) {
          return Container(
            width: 380,
            color: const Color(0xFFFDECE9),
            padding: const EdgeInsets.all(24.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Header
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      'Active Order',
                      style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, letterSpacing: -0.5),
                    ),
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                      decoration: BoxDecoration(
                        color: Colors.white.withValues(alpha: 0.5),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: const Text(
                        '#4921',
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12, color: Colors.black54),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 32),

                // 2. Dynamic Order Items List
                Expanded(
                  child: cartState.items.isEmpty
                  // Show this if the cart is empty
                      ? Center(
                    child: Text(
                      'Cart is empty.\nTap a product to start.',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Colors.grey[600]),
                    ),
                  )
                  // Show the list of items if we have them
                      : ListView.builder(
                    itemCount: cartState.items.length,
                    itemBuilder: (context, index) {
                      final item = cartState.items[index];
                      return Padding(
                        padding: const EdgeInsets.only(bottom: 16.0),
                        child: _buildCartItem(item), // Pass the whole CartItem object
                      );
                    },
                  ),
                ),

                // 3. Dynamic Totals & Checkout
                Column(
                  children: [
                    _buildSummaryRow('Subtotal', '\$${cartState.subtotal.toStringAsFixed(2)}'),
                    const SizedBox(height: 8),
                    _buildSummaryRow('Tax (8%)', '\$${cartState.tax.toStringAsFixed(2)}'),
                    const SizedBox(height: 16),

                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text('Total Due', style: TextStyle(fontSize: 16)),
                        Text(
                            '\$${cartState.total.toStringAsFixed(2)}',
                            style: const TextStyle(fontSize: 32, fontWeight: FontWeight.bold)
                        ),
                      ],
                    ),
                    const SizedBox(height: 24),

                    // Note & Discount Buttons
                    Row(
                      children: [
                        Expanded(child: _buildSecondaryButton(Icons.note_add_outlined, 'Note')),
                        const SizedBox(width: 12),
                        Expanded(child: _buildSecondaryButton(Icons.local_offer_outlined, 'Discount')),
                      ],
                    ),
                    const SizedBox(height: 16),

                    // Checkout Button
                    SizedBox(
                      width: double.infinity,
                      height: 64,
                      child: ElevatedButton.icon(
                        // Disable the button if the cart is empty
                        // Checkout Button Logic
                          onPressed: cartState.items.isEmpty ? null : () {
                            // 1. Show a success popup
                            showDialog(
                              context: context,
                              barrierDismissible: false, // Forces them to click the button to close
                              builder: (BuildContext dialogContext) {
                                return AlertDialog(
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                                  title: const Row(
                                    children: [
                                      Icon(Icons.check_circle, color: Color(0xFF006E3B), size: 28),
                                      SizedBox(width: 8),
                                      Text('Payment Successful', style: TextStyle(fontWeight: FontWeight.bold)),
                                    ],
                                  ),
                                  content: Text(
                                    'Order #4921 has been sent to the barista.\nTotal charged: \$${cartState.total.toStringAsFixed(2)}',
                                    style: const TextStyle(fontSize: 16),
                                  ),
                                  actions: [
                                    SizedBox(
                                      width: double.infinity,
                                      height: 48,
                                      child: ElevatedButton(
                                        style: ElevatedButton.styleFrom(
                                          backgroundColor: const Color(0xFF006E3B),
                                          foregroundColor: Colors.white,
                                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                        ),
                                        onPressed: () {
                                          // 2. Clear the cart data
                                          cartState.clearCart();
                                          // 3. Close the popup
                                          Navigator.of(dialogContext).pop();
                                        },
                                        child: const Text('Start New Order', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                                      ),
                                    ),
                                  ],
                                );
                              },
                            );
                          },
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF006E3B),
                          foregroundColor: Colors.white,
                          disabledBackgroundColor: Colors.grey[400], // Grey out when empty
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(16),
                          ),
                          elevation: 0,
                        ),
                        icon: const Icon(Icons.contactless_outlined),
                        label: const Text(
                          'Checkout',
                          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          );
        }
    );
  }

  // Helper updated to take a CartItem and calculate dynamic line totals
  Widget _buildCartItem(CartItem item) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(item.product.name, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                const SizedBox(height: 4),
                Text(item.modifiers, style: TextStyle(color: Colors.grey[600], fontSize: 12)),
                const SizedBox(height: 16),

                // Quantity Controls (- 1 +) wired to the cartState
                Row(
                  children: [
                    _buildQtyButton(Icons.remove, () => cartState.updateQuantity(item, -1)),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      child: Text('${item.quantity}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                    ),
                    _buildQtyButton(Icons.add, () => cartState.updateQuantity(item, 1)),
                  ],
                ),
              ],
            ),
          ),
          Text(
              '\$${(item.product.price * item.quantity).toStringAsFixed(2)}',
              style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)
          ),
        ],
      ),
    );
  }

  // Added onTap parameter so the buttons actually work
  Widget _buildQtyButton(IconData icon, VoidCallback onTap) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(8),
      child: Container(
        padding: const EdgeInsets.all(6),
        decoration: BoxDecoration(
          color: const Color(0xFFFDECE9),
          borderRadius: BorderRadius.circular(8),
        ),
        child: Icon(icon, size: 14, color: Colors.black87),
      ),
    );
  }

  Widget _buildSummaryRow(String label, String value) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(label, style: TextStyle(color: Colors.grey[700], fontSize: 14)),
        Text(value, style: TextStyle(color: Colors.grey[800], fontSize: 14)),
      ],
    );
  }

  Widget _buildSecondaryButton(IconData icon, String label) {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 14),
      decoration: BoxDecoration(
        color: const Color(0xFFF3D8D3),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(icon, size: 18, color: Colors.black87),
          const SizedBox(width: 8),
          Text(label, style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.black87)),
        ],
      ),
    );
  }
}